### PR TITLE
custom_cell_representation

### PR DESCRIPTION
**Pull request by NormanDenayer**
and the custom cell representation seems very interesting (at least for me).

### CODE REVIEW

**Comment by Imballinst** [comment]
I was a bit skeptical about this, but when I thought about it again earlier this morning, true, sometimes we want to left the raw data unmodified. I think this is a really good feature. Great job!

Anyway, what do you think should I do with the old feature (`tableBody` can handle React Components and such)? Should I keep it? Personally, I would like to keep it for the time being; so the user can choose based on their needs.

**Comment by NormanDenayer** [comment]
Thank you.
100% agree with you, the user may be able to choose. So the « old » feature should remain.

**Comment by Imballinst** [comment]
Alright, I will merge this soon :+1:

**Comment by Imballinst** [comment]
This PR has been merged along with #9. Thanks @NormanDenayer!

**Pull request merged**
